---
# file: oracle-java/tasks/main.yml
#
# tasks file
#

- name: check host environment
  include: check_environment.yml

- include: debug.yml
  when: debug | default(false)
  tags: debug

- name: download Java RPM
  get_url:
    url:     "{{ oracle_java_rpm_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
  register: oracle_java_task_rpm_download
  become: true
  tags:
    - installation

- name: install RPM
  action: "{{ ansible_pkg_mgr }} name={{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} state=present"
  when: not oracle_java_task_rpm_download|skipped
  become: true
  tags:
    - installation

- name: set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  become: true
  when: (
          oracle_java_set_as_default and
          oracle_java_task_rpm_download is defined and
          oracle_java_task_rpm_download|changed
        ) or (
          oracle_java_set_as_default and
          oracle_java_installed is defined and
          oracle_java_installed and
          oracle_java_version_installed is defined and
          oracle_java_version_installed != oracle_java_version_string)
  register: oracle_java_task_set_default
  tags:
    - skip_ansible_lint

- name: in case there were changes, check host environment again
  include: check_environment.yml
  when: (
          oracle_java_task_rpm_download is defined and
          not oracle_java_task_rpm_download|skipped
        ) or (
          oracle_java_task_set_default is defined and
          oracle_java_task_set_default|changed
        )
