---
# file: oracle-java/tasks/main.yml
#
# tasks file
#

- name: check host environment
  import_tasks: check_environment.yml

- import_tasks: debug.yml
  when: debug | default(false)
  tags: debug

- import_tasks: install.yml
  when: (oracle_java_upgrade_package == true) or (oracle_java_installed == false)