---
# file: oracle-java/tasks/main.yml
#
# tasks file
#

- name: check host environment
  include: check_environment.yml

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: install.yml
  when: (oracle_java_upgrade_package == true) or (oracle_java_installed == false)